### ISSUE TITLE
Some very small sophistication

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#1]
Hi!

As nowadays I made (and I'm in progress in some of them) some polishing processes in some Gnome Shell extensions to make the result as perfect as it can, maybe I will PR my thoughts later if I have enough time for it but the extension itself I thing is perfect if you change the layout.

Until it I just suggest to use maybe this MDI icon as extension icon on extensions.gnome.org:
https://materialdesignicons.com/icon/power-settings
_(Maybe in custom colors if you want but the base black (or a soft dark grey) could be homogenous for long live between the other extensions what use simple and nice icons for it.)_

You can put some lines about the icon license into the README like we do here:
https://github.com/lachhebo/corona-tracker

And the final result could be perfect.

Anyway thanks again for your efforts!

**Comment by pratap-panabaka** [comment]
Thanks for your comment. I would like to know the way you want the layout to be.
I am  going through your suggestion about the MDI Icon. May be I will finish it in couple of hrs.
