### ISSUE TITLE
Error after upgrade extesion on Ubuntu 20.04

### ISSUE THREAD

**Issue by neapovea** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#10]
Hi, the extensions fail on upgrade in Ubuntu 20.04. Here paste the trace:

> Jul  2 09:44:11 gnome-shell[26021]: Archive:  /tmp/1JSYM0.shell-extension.zip
> Jul  2 09:44:11 gnome-shell[26021]:   inflating: /home/alternate/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/compile-schemas-script
> Jul  2 09:44:11 gnome-shell[26021]:    creating: /home/alternate/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/schemas/
> Jul  2 09:44:11 gnome-shell[26021]:   inflating: /home/alternate/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/schemas/org.gnome.shell.extensions.brngout.gschema.xml
> Jul  2 09:44:11 gnome-shell[26021]:   inflating: /home/alternate/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/schemas/gschemas.compiled
> Jul  2 09:44:11 gnome-shell[26021]:   inflating: /home/alternate/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/extension.js
> Jul  2 09:44:11 gnome-shell[26021]:  extracting: /home/alternate/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/metadata.json
> Jul  2 09:44:11 gnome-shell[7038]: Attempting to remove actor of type 'Gjs_ui_popupMenu_PopupImageMenuItem' from group of class 'StBoxLayout', but the container is not the actor's parent.
> Jul  2 09:44:11 gnome-shell[7038]: message repeated 4 times: [ Attempting to remove actor of type 'Gjs_ui_popupMenu_PopupImageMenuItem' from group of class 'StBoxLayout', but the container is not the actor's parent.]
> Jul  2 09:44:11 gnome-shell[7038]: JS ERROR: Extension BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm: Error: GSettings key show-gnome-tweaks not found in schema org.gnome.shell.extensions.brngout#012_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:576:23#012_init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:528:30#012_nextAction@/home/alternate/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/extension.js:84:58#012wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27#012_takeAction@/home/alternate/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/extension.js:63:6#012wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27#012_init@/home/alternate/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/extension.js:35:7#012wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27#012enable@/home/alternate/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/extension.js:113:16#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:336:26#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:39#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
> 

Ciao, thanks.

**Comment by pratap-panabaka** [comment]
Hi, can you run two commands as mentioned in the readme.md of v9 please..
