### ISSUE TITLE
Great addon but unfortunately breaks the Hibernate Status Button addon

### ISSUE THREAD

**Issue by 6000years** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#12]
The addon Hibernate Status Button ( https://extensions.gnome.org/extension/755/hibernate-status-button/ ) adds a Hibernate button to the Power Off / Log Out menu.

Bring Out Submenu unfortunately doesn't detect the Hibernate button, so the two addons can't be used together. Shame.

**Comment by pratap-panabaka** [comment]
Hi, I have gone through the extension you mentioned.. If you wish you have both the extensions work together..as a quick workaround open the file `$HOME/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js` look for the lines around 175 to 199 and edit the contents with below content.. you may use any valid icon you wish in place of `system-hibernate` in the below lines..

![](https://i.stack.imgur.com/zJkv7.jpg)

````    
    enable() {
        this._checkRequirements();
        this._loginManager = LoginManager.getLoginManager();
        this.systemMenu = Main.panel.statusArea['aggregateMenu']._system;

        this._hibernateMenuItem = new PopupMenu.PopupImageMenuItem(_('Hibernate'), 'system-hibernate');
        this._hibernateMenuItemId = this._hibernateMenuItem.connect('activate', Lang.bind(this, this._onHibernateClicked));

        this._hybridSleepMenuItem = new PopupMenu.PopupImageMenuItem(_('Hybrid Sleep'), 'system-hibernate');
        this._hybridSleepMenuItemId = this._hybridSleepMenuItem.connect('activate', Lang.bind(this, this._onHybridSleepClicked));

        let afterSuspendPosition = this.systemMenu.menu.numMenuItems - 1;

        this.systemMenu.menu.addMenuItem(this._hybridSleepMenuItem, afterSuspendPosition);
        this.systemMenu.menu.addMenuItem(this._hibernateMenuItem, afterSuspendPosition);

        this._menuOpenStateChangedId = this.systemMenu.menu.connect('open-state-changed', Lang.bind(this,
            function (menu, open) {
                if (!open)
                    return;
                this._hibernateMenuItem.visible = true;
                this._updateHaveHibernate();
                this._updateHaveHybridSleep();
            }));
    }

````
If you wish to have the buttons in between suspend and power off buttons.. you need to add this command to your startup application preferences..

````
gnome-extensions reset hibernate-status@dromi && gnome-extensions enable hibernate-status@dromi
````
![](https://i.stack.imgur.com/rMfN5.jpg)

![](https://i.stack.imgur.com/GnkgW.png)

**Comment by 6000years** [comment]
Pratap,
Thanks for taking notice of this.
I've applied the code changes and my extensions.js now looks like this:

````
enable() {
this._checkRequirements();                                                                                                                                                                              
this._loginManager = LoginManager.getLoginManager();
this.systemMenu = Main.panel.statusArea['aggregateMenu']._system;
     
this._hibernateMenuItem = new PopupMenu.PopupImageMenuItem(_('Hibernate'), 'system-hibernate');
this._hibernateMenuItemId = this._hibernateMenuItem.connect('activate', Lang.bind(this, this._onHibernateClicked));
     
this._hybridSleepMenuItem = new PopupMenu.PopupImageMenuItem(_('Hybrid Sleep'), 'system-hibernate');
this._hybridSleepMenuItemId = this._hybridSleepMenuItem.connect('activate', Lang.bind(this, this._onHybridSleepClicked));
     
let afterSuspendPosition = this.systemMenu.menu.numMenuItems - 1;
     
this.systemMenu.menu.addMenuItem(this._hybridSleepMenuItem, afterSuspendPosition);
this.systemMenu.menu.addMenuItem(this._hibernateMenuItem, afterSuspendPosition);
     
this._menuOpenStateChangedId = this.systemMenu.menu.connect('open-state-changed', Lang.bind(this,
function (menu, open) {
if (!open)
return;
this._hibernateMenuItem.visible = true;
this._updateHaveHibernate();
this._updateHaveHybridSleep();
}));
}
````

I also ran the reset command line, and re-enabled Hibernate Status via the gnome extensions web page, but the hibernate button does not work. I can't find any errors anywhere, either in syslog or in looking glass.

Is there some other step to complete, such as zipping up the extension.js file into a zip file?

**Comment by pratap-panabaka** [comment]
Hey.. If the menu is showing the 2 buttons.. Thats it for the workaround of combining both the extensions to work..

There is a workaround for the problem you have in the hibernate extension link.. you need to go through that..
see the workaround from this link https://github.com/arelange/gnome-shell-extension-hibernate-status

> 
> Hibernation button does not show up, but systemctl hibernate works
> 
> If you are running Ubuntu, try putting
> 
> [Enable hibernate in upower]
> Identity=unix-user:*
> Action=org.freedesktop.upower.hibernate
> ResultActive=yes
> 
> [Enable hibernate in logind]
> Identity=unix-user:*
> Action=org.freedesktop.login1.hibernate;org.freedesktop.login1.handle-hibernate-key;org.freedesktop.login1;org.freedesktop.login1.hibernate-multiple-sessions;org.freedesktop.login1.hibernate-ignore-inhibit
> ResultActive=yes
> 
> into /etc/polkit-1/localauthority/10-vendor.d/com.ubuntu.desktop.pkla

**Comment by 6000years** [comment]
I don't think it's that. The Hibernate Status Button addon works fine on its own (ie if Bring Out Submenu is not active). The buttons for Hibernate and Hybrid Sleep appear, and they work.

Is it possible that gnome shell needs to be reset, in order to recognise changes made in extension.js?

**Comment by pratap-panabaka** [comment]
Oh sorry I thought the extension didn't work on its own and thats why wrote above comment.. 

yes Alt+F2 r Enter required after editing extension.js file.. but when you run the command reset && enable.. It should work.. but I dont think Bringout Extension is the cause..

**Comment by 6000years** [comment]
Brilliant !  The Alt F2 r fixes it.
Updates to Hibernate Status Button will overwrite your changes unfortunately, but I'll live with it.

**Comment by pratap-panabaka** [comment]
when gnome-shell refreshes.. the buttons go there.. so you need to run reset && enable full command.. if you make the command as startup application preferences.. the order will survive reboots n logout.. Thank You!!!

````
gnome-extensions reset hibernate-status@dromi && gnome-extensions enable hibernate-status@dromi
````

**Comment by pratap-panabaka** [comment]
yes updates to the Hybernate extension will overwrite our workaround.. You can hold updates by renaming the extension name and editing that name in `metadata.json` file under `uuid:`

**Comment by juxuanu** [comment]
What about integrating this as default? Or through a toggle in the extension settings?

**Comment by 6000years** [comment]
That  would certainly be helpful to any Hibernate Status Button user. But might it be difficult to query whether the Hibernate button is present in the menu or not, before re-adding it?

**Comment by juxuanu** [comment]
Well, I'm talking about adding the hibernate code in this extension and having a config to toggle the visibility.

**Comment by 6000years** [comment]
I see. That's a better idea. It's arguably feature creep, but that
doesn't mean it's wrong.
