### ISSUE TITLE
Missing 'restart' option on Gnome 3.38

### ISSUE THREAD

**Issue by fuelflo** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#13]
Hey, I like the add-on. But on Gnome 3.38 it removes the restart option, any chance to add that to the menu?

**Comment by pratap-panabaka** [comment]
Hi, I have added 3.38 Branch, Please test it.

![Screenshot from 2020-10-30 19-52-40](https://user-images.githubusercontent.com/40719899/97716391-91c15200-1ae9-11eb-815c-9f25ad510f3e.png)

**Comment by fuelflo** [comment]
Works perfectly, thx!
So i think this could be released on extensions.gnome.org for 3.38.

**Comment by pratap-panabaka** [comment]
Yes. I have tested it few weeks ago. Bit busy and waited for Ubuntu 20.10 release. Will upload soon. Thanks for your response.
