### ISSUE TITLE
lock should be moved to lext group

### ISSUE THREAD

**Issue by rudrab** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#16]
Dear Developers,
Thanks for this very essential extension.
I have one request though. 
In current settings (with extension and tweak in menu is almost default), may I request to bring lock item below seperator 1? 
**Currently the arrangement is like:**
extension
tweak
setting
lock
**---sep 1---**
suspend
restart
poweroff
**---sep 2---**
logout

**It would be better if  we have**
extension
tweak
setting
**---sep 1---**
lock
suspend
restart
poweroff
**---sep 2---**
logout

In that way, all settings will be under one block, and afk's are in another..

**Comment by pratap-panabaka** [comment]
Hi, Thanks for your suggestion. I have gone through your suggestion and found that once you install tweaks & extensions gnome-shell extension, you have configured the values like below.

![Screenshot](https://user-images.githubusercontent.com/40719899/120583758-72f2b780-c44c-11eb-9873-2eb8ba627dfa.png)

I will try to see how to bring the lock below separator 1 in some time.

**Comment by pratap-panabaka** [comment]
open the file `$HOME/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/extensions.js` find the below content and at line no 83. Add below line

`systemMenu.moveMenuItem(System._lockScreenItem, 3);`

![Screenshot from 2021-06-03 10-18-48](https://user-images.githubusercontent.com/40719899/120588643-265faa00-c455-11eb-9004-d362564a0e32.png)

Save the file and restart the gnome-shell with Alt+F2 r enter Method.

Please note that when ever you disable or enable this extension. gnome-shell refresh is required. Use Alt+F2 r enter Method.

![Screenshot from 2021-06-03 10-21-39](https://user-images.githubusercontent.com/40719899/120588843-835b6000-c455-11eb-960d-bb89d390e284.png)

**Comment by pratap-panabaka** [comment]
In that way, all settings will be under one block, and afk's are in another..

What is afk, I am curious to know this.

**Comment by rudrab** [comment]
@PRATAP-KUMAR away from keyboard :)

**Comment by pratap-panabaka** [comment]
Ok Thank You.
Have you tried about adding the line?

**Comment by rudrab** [comment]
yes...but somehow, bu adding that line it taking "Lock" above of the "Settings", just below "Tweaks". Also, our settings look different  (I am using the version from gnome-extensions).

**Comment by pratap-panabaka** [comment]
OK, I Understand. In that case you need to change the position `3` in this line to your suitable value by trail and error. Only gnome-shell refresh with Alt+F2 r Enter method is required after every trail and error value. Once it suits your position. Nothing to do.

`systemMenu.moveMenuItem(System._lockScreenItem, 3);`

**Comment by rudrab** [comment]
Thanks. Solved.
