### ISSUE TITLE
New upate broke the extension. (pop_os 21.04).

### ISSUE THREAD

**Issue by satyamm1001** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#17]
After installing the update extension shows error on the website(gnome shell org). It was working absolutely fine before please fix it asap. It's a very helpful extension.

**Comment by pratap-panabaka** [comment]
Hi, today I have done Major changes with shell versions 3.36 3.38 and 40. I have tested all of them. First remove the extension and then Can you download the extension from https://extensions.gnome.org/extension/2917/bring-out-submenu-of-power-offlogout-button/ by choosing your shell version and report back please.

**Comment by satyamm1001** [comment]
Hey, somehow the link provided by you worked pretty well. Thanks for help!
