### ISSUE TITLE
Breaks "Hibernate Status Button" extension

### ISSUE THREAD

**Issue by root2185** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#19]
```
Debian 11
GNOME Shell 3.38.4
```
The extension "Hibernate Status Button" ( https://extensions.gnome.org/extension/755/hibernate-status-button/ ) adds the `Hibernate` and `Hybrid Sleep` buttons to the Power Off / Log Out menu.

When I use "Bring Out Submenu" the extra buttons vanish, as reported here https://github.com/PRATAP-KUMAR/Bring-Out-Submenu-of-Power-Off-Logout/issues/12.

Can you integrate the other extension into yours? Both should be enabled by default in GNOME.

**Comment by pratap-panabaka** [comment]
Hi, I have gone through your comment and tried to work out to Integrate both the extensions. Still need to test it.
I Suggest you to try this Extension.

[hibernateBringOut.zip](https://github.com/PRATAP-KUMAR/Bring-Out-Submenu-of-Power-Off-Logout/files/7017122/hibernateBringOut.zip)

while integrating, I am still not able to call that Check when we click on "Hibernate" from the hibernate extension. Be careful before clicking the Hibernate button as it wont give chance to confirm.

![hibernate](https://user-images.githubusercontent.com/40719899/130128107-21fa37c3-0d16-42c1-84ac-a70fbac903c2.png)

once you downloaded the zip file, from the same directory
run
````
gnome-extensions install -f hibernateBringOut.zip
````

**Comment by root2185** [comment]
Nice, after the extension is tested and uploaded officially I can simply upgrade it, I have a shortcut for hibernate and I don't use hybrid sleep.

I have a lot of extensions and I would like to sort them, an important thing as pointed out here https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/402

So I am searching someone that can make an extension, can you do it maybe?
I am not a developer.

**Comment by pratap-panabaka** [comment]
Hi, Plz do install the extension I have linked in GitHub comments that you raised an Issue. Uploading it officially takes time bcoz I need to sort out that confirmation Dialog.

Regarding top bar, as the comments said It's not possible from my side too for DND but if you can provide me the real case I will try it. Real case, I mean how is your top bar looking and how would you like to arrange the icons position etc.

**Comment by root2185** [comment]
I installed it, it works.

Is it possible maybe to make an extension that allow to move them on the left, center or right?

**Comment by pratap-panabaka** [comment]
I am not clear.. mv from left right center?
Can you show a picture so that I will start trying it now.

**Comment by root2185** [comment]
![Screenshot from 2021-08-18 20-01-27](https://user-images.githubusercontent.com/32654091/130274957-8e80ce73-dced-4c92-962f-1b5af7b3dc04.png)
Is it possible to make an extension that allow that with all the other extensions in the top bar?

**Comment by pratap-panabaka** [comment]
That's possible only by tweaking those each extension which is defining their positions. IMHO it's not possible to control those positions by creating another extension.

**Comment by pratap-panabaka** [comment]
Hi,
Please Check this one.
https://github.com/PRATAP-KUMAR/save-local-gnome-extension-settings/blob/main/README.md

**Comment by root2185** [comment]
Hi,
IS there a list of files to be saved then? I checked the script.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pratap-panabaka** [comment]
I have made the script to get the current extension settings. No need to do anything. When ever you run the script, that time values will be updated in the directory. Yes if you want to store different times.. copy paste the created directory in a different location.

**Comment by pratap-panabaka** [comment]
At different times when you want to save the settings..

Create a directory named with time and date, then copy importSettings.sh and saved Settings directory.

savedSettings directory holds the settings when you trigger saveSettings.sh

To import those settings from savedSettings directory you need to run the script importSettings.sh

importSettings.sh script and savedSettings directory must be side by side.

This means you need savedSettings directory and importSettings.sh with different directory named.

For example,  the directories
24.Aug.21_10am
24.Aug.21_11am
25.Aug.21_12am
Etc. Each directory will have importSettings.sh and savedSettings directory.

**Comment by root2185** [comment]
Does it save also the tweaks, Settings and dconf settings?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by root2185** [comment]
Hello,

I tried to use your script to save gnome settings but it didn't work.
Anyway now I use Openbox.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
