### ISSUE TITLE
Gnome crash when using touch on top panel system menu

### ISSUE THREAD

**Issue by roiz-git** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#2]
It's awfully strange, when the extension is on, and i use the touch gesture in order to get to the system menu of the top bar panel. Gnome crashes 

Gnome 3.36.1
Wayland 1.18

**Comment by pratap-panabaka** [comment]
hi sorry to know about that. what is the command u r using to achieve with the touch gesture.

**Comment by roiz-git** [comment]
I have a touch screen on my Lenovo thinkpad, I do not use commands

**Comment by pratap-panabaka** [comment]
I am sorry, I did understood that you have configured some command with your first comment. So you are simply touching the area where network,sound and power-off button located rite.

**Comment by roiz-git** [comment]
yes, I think there's some combination with Gnome Dim Screen feature (due to inactivity)...can't tell for sure

**Comment by pratap-panabaka** [comment]
0k thats a nice info from you. I will try to see if I can reproduce this.. Thanks for reporting the issue here.

**Comment by pratap-panabaka** [comment]
Hi.. Can you chk with latest update of the extension.. is it still happening?

**Comment by roiz-git** [comment]
I think you managed to fix it, I have been using it for half a day now with no issues.
I will reopen the issue if it will come back again
Many thanks

**Comment by pratap-panabaka** [comment]
roizcorp, thank you for your response.. It really helped me to remove the older version of the extension.. I will wait for one more day.. you please see it and report back if the issue comes back. Thanks a lot..
