### ISSUE TITLE
Can't install upgrade - "ERROR" with no other info

### ISSUE THREAD

**Issue by wjandrea** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#22]
I tried upgrading, but the site said "ERROR". So I uninstalled and tried reinstalling, but the same thing happened. The site gives no other details, which is totally unhelpful. How could I get you more details?

I'm using GNOME Shell 3.36.9 on Ubuntu 20.04.

Screenshot:
![Capture d’écran de 2022-02-04 19-08-26](https://user-images.githubusercontent.com/22385371/152619316-ef466bbe-718a-4732-b9e3-cc9cca8a5ca5.png)

**Comment by wjandrea** [comment]
I ended up uninstalling it, restarting GNOME Shell (Alt-F2, `r`), and reinstalling. Now it's fine.

**Comment by pratap-panabaka** [comment]
@wjandrea nice to see you here on github. Your user ID is well known to me in AskUbuntu.
