### ISSUE TITLE
Switch User not working

### ISSUE THREAD

**Issue by JensWagner07** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#23]
Since updating to Ubuntu 22.04 this extension did not work for Entry 'Switch User'. If i click on it, the menu disapear but nothing happen!
If I turn of this extension it works fine! Maybe a translation issue because I use Ubuntu in German?

System Ubuntu 22.04 Gnome 42.0

**Comment by pratap-panabaka** [comment]
Hi..
I didt install Ubuntu 22.04 yet..
I will install it in few days and rectify it.
IMHO Translation may not be an issue.
But Something which can be rectified once I Use the extension in Ubuntu 22.04

Mean while can you provide the output of below command please.

`gnome-shell --version`

Thank You for reporting.

**Comment by pratap-panabaka** [comment]
If you don't mind.
Can you disable BringOutSubMenu Extension and 
Can you install this extension https://extensions.gnome.org/extension/4693/rounded-system-menu-buttons/ and see if the switch user working or not? It gives me a easy clue before I download and install Ubuntu 22.04 to rectify BringOutSubMenu Extension.

Thanks

**Comment by JensWagner07** [comment]
Hi,
output of 'gnome-shell --version' is 'GNOME Shell 42.0'
The mentioned Extension 'Rounded System Menu Button' works fine including the 'Switch User' entry!!!

**Comment by pratap-panabaka** [comment]
Hi, I am installing 22.04 Now..
Thanks for the above info.

Will revert in few hours about Switch User entry..

**Comment by pratap-panabaka** [comment]
Hi,
There is a typo error for Switch User.. "activat" vs "activate".

I have uploaded it to gnome-extensions website for approval.
I hope in few hours it will be approved and your extension version will also updated.

if you wish to change it now, open the below file and correct it according to image (line no 120 in the image).
`$HOME/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/extension.js`

![Screenshot from 2022-05-10 20-55-57](https://user-images.githubusercontent.com/40719899/167665209-40b78131-fe71-4ce7-9c93-70ab679561a7.png)

**Comment by JensWagner07** [comment]
Cool, it's working now perfectly! Thanks for very fast help!

**Comment by JensWagner07** [comment]
Works fine for me now!
