### ISSUE TITLE
Please update for version 43

### ISSUE THREAD

**Issue by horga83** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#25]
Can you update for 43 so we can have a LOGOUT in the menu or by quick settings button.

**Comment by pratap-panabaka** [comment]
Hey,
Will start working on this from tomorrow.
I will update you once I get some output.

**Comment by pratap-panabaka** [comment]
Hi @horga83 @xuedi @kapitansen I have just tested it and made a simple one which works for default `gnome-shell` version `43`.
Will try to work on settings of this extension when I get free time after 10 days.

![image](https://user-images.githubusercontent.com/40719899/201060438-74d9a34c-e915-46b9-8712-69f37ed6dfbb.png)

I have uploaded it to `gnome-extensions` website, once it is approved, It will be shown to public.

Thank you for raising this issue.

**Comment by horga83** [comment]
Thank you kindly for your work on this, we appreciate it.

Cheers
George

**Comment by freak007** [comment]
Many thanks for gnome43 update. Is it possible to enable extension for all monitors, because it's only enable on primary monitor ?
Best regards.

**Comment by pratap-panabaka** [comment]
Hi Freak, @freak007 at my level of knowledge I can not make it. I mean I dont know how to implement that as I am in learning stage now.

Is the top bar with all elements shown on all monitors in your case? I mean Activities, Date, SystemMenu?
