### ISSUE TITLE
[Feature request] Add settings

### ISSUE THREAD

**Issue by somepaulo** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#26]
Please consider implementing user settings to choose which buttons to show/hide and maybe the order of the buttons.
Thank you!

**Comment by pratap-panabaka** [comment]
I hope to start this after 10 days, thank you @somepaulo

**Comment by pratap-panabaka** [comment]
@somepaulo :raised_hand_with_fingers_splayed: 

I just finished settings for (hide/show) those 4 buttons SUSPEND, LOGOUT, RESTART and POWER.  
GNOME is under maintenance, so I am not able to upload the extension for review. But here is the branch https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/tree/feature/remove-add-buttons if you wish you try it until I upload it to gnome-extension for review.

![image](https://user-images.githubusercontent.com/40719899/202539506-7f1c144f-6bf5-4467-8d80-1d15ffec79d2.png)

Thank You.

**Comment by pratap-panabaka** [comment]
@somepaulo :raised_back_of_hand: 
I will try to work on ordering of the buttons in weekends after this week.

Thank You.
