### ISSUE TITLE
Enhancement proposal: Dis-/Enable confirmation dialog

### ISSUE THREAD

**Issue by klslz** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#29]
Thx for the extension. 

It brings the annoying 4-click power-off procedure of Gnome one level down.

Now. We could gain another click. 
By disabling the confirmation dialog we'd be down to two clicks for power-down. 

It can simply be done this way: (That's what I am doing manually)

```
gsettings set org.gnome.SessionManager logout-prompt false
gsettings set org.gnome.SessionManager logout-prompt true

gsettings get org.gnome.SessionManager logout-prompt

```

Would be great if you'd consider introducing a tick box in your settings menu to also turn the 
confirmation dialog on/off.

Thx  (I know many people would appreciate it)

**Comment by pratap-panabaka** [comment]
Hi @klslz

I have made those changes and one thing bothered me is inverse selection. I mean if user tries to use command line or dconf to change org.gnome.SessionManager logout-prompt, it will have a conflict. For this I made a work around for time being. I tried a lot to avoid this but I could not. Anyways just try the new update from gnome-extensions.

Lets see if something wrong with this update.

Thanks

**Comment by klslz** [comment]
That was quick. Just tested it. 

The update concluded with an error (red error symbol on the extension site). ( I had the confirmation "off" at update)
And the extension got disabled - I guess due to the error. 

However. I rebooted and the updated extension showed up. 

I did a quick regression test. It seems to work. 

Perhaps you could consider a slightly more serious looking tick box description text. ;) 

Anyhow. Thx for the effort.  Now we're down to 2-clicks!! Great.

**Comment by pratap-panabaka** [comment]
Oh yes.. I have to improve the text message and also I understood why the error showed up. I will look into. U dont need reboot with extensions. If u r using X server then alt+f2 and then r is enough and in wayland server logout is enough.
