### ISSUE TITLE
Conflict with battery time extension

### ISSUE THREAD

**Issue by Eeems** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#30]
According to a user review on extensions.gnome.org for the [battery time](https://extensions.gnome.org/extension/1475/battery-time/) extension, this extension conflicts with it when running in GNOME Shell 44.

Upon testing myself, it does seem to keep this extension from working if battime is loaded first. There are no errors visible through looking glass.

I've also opened https://github.com/mzur/gnome-shell-batime/issues/14

**Comment by Eeems** [comment]
Upon a quick review of the code, it could be because `Panel.statusArea.quickSettings._system` is replaced by a new power indicator by the battery time extension. This was a change I made to make debugging easier in the battery time extension. I'll ask for it to be changed, and sort out a better way to expose the battery time version of the indicator.

**Comment by pratap-panabaka** [comment]
@Eeems thanks for the issue.
I am in doubt whether I have to do any changes or the other extension needs change?
If I have to, I am ready.

**Comment by Eeems** [comment]
To fix this the other extension needs to change. I've already submitted a PR.

It might be worth sorting out why no exception was raised though and better detecting if it fails to initialize.
