### ISSUE TITLE
v41 not working on GNOME Shell 44.3

### ISSUE THREAD

**Issue by shimarulin** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#31]
After update to v41 I got an error from this extension:

> Expected an object of type ClutterActor for argument 'child' but got type undefined

❯ gnome-shell --version
GNOME Shell 44.3

I downgraded this extension to v39 and it works well.

**Comment by pratap-panabaka** [comment]
Hi @shimarulin 
May I know your linux distribution and have you tried logging out and login back once you get the v41?

**Comment by leachimus** [comment]
Same problem here

Error: Expected an object of type ClutterActor for argument 'child' but got type undefined.

Fedora 38, GNOME 44.3
Several reboots performed. Without success

Please fix it

**Comment by shimarulin** [comment]
Hi @PRATAP-KUMAR ! I use Arch Linux, some info:

```
~
❯ cat /etc/os-release | grep "^NAME"
NAME="Arch Linux"

~ 
❯ echo $XDG_SESSION_TYPE
x11

~
❯ hostnamectl | grep Kernel                                  
          Kernel: Linux 6.1.39-1-lts
```

Logout/login and reboot does not solve the problem

**Comment by shimarulin** [comment]
I'm using X11 because Wayland still doesn't work very well for comfortable use for me (eg Tilix quake-mode doesn't work and some others).

**Comment by pratap-panabaka** [comment]
Hi @shimarulin I too use Arch Linux. I tested it in several edge cases before submitting it for review. I need to install some other linux distro for ex. Fedora as mentioned by @leachimus to see the cause. I will install and check the problem. Thanks

**Comment by jspitz** [comment]
Same problem here. OpenSuse Tumbleweed, GNOME Shell 44.3, Wayland.

**Comment by leachimus** [comment]
Some more info from me as well:
```

[leachimus@fedora ~]$ bat /etc/os-release | grep "^NAME"
NAME="Fedora Linux"

[leachimus@fedora ~]$ echo $XDG_SESSION_TYPE
wayland

[leachimus@fedora ~]$ hostnamectl | grep Kernel
 Kernel: Linux 6.3.12-200.fc38.x86_64
```

**Comment by pratap-panabaka** [comment]
Hi @shimarulin @leachimus @jspitz may I know your system languages? the change I made from v39 and v41 has something related to system language, so it will be helpful for me if your system languages are in English or other? Thanks

**Comment by pratap-panabaka** [comment]
v41 of this extension worked for me in Arch Linux with gnome-shell v44.3 and in Ubuntu with gnome-shell v44.0. I will try to solve this anyhow. Thanks

**Comment by jspitz** [comment]
@PRATAP-KUMAR system language here is `de_DE.utf-8`, LC_NUMERIC is `de_AT.utf-8`. More precisely:
```
locale
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER=de_AT.UTF-8
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by shimarulin** [comment]
❯ locale   
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=

**Comment by pratap-panabaka** [comment]
Ok thanks for the info. It helped me a lot to understand what is wrong. Now I can work on it.

**Comment by pratap-panabaka** [comment]
I have updated the extension and submitted for review. Once it is approved, v42 of this extension will resolve it hopefully.
Thanks

**Comment by leachimus** [comment]
Yes, of course. I use the system in German language, like the others do

**Comment by shimarulin** [comment]
@PRATAP-KUMAR I got the extension upgrade to v43 and it works great! Thanks a lot for such a quick fix! It made my day better!
