### ISSUE TITLE
Switch user option and text overlay

### ISSUE THREAD

**Issue by luca-brambilla** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#32]
Hi!

I am not able to disable the "Switch user" option after bringing out the sub menu.
Also the text overlay that appears is not readable on the outermost button.

Is there any way to fix this? Thanks! :)

Screenshot
![Screenshot from 2023-10-30 23-10-33](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/72706042/ff0414f8-c197-4fb6-9ebc-19a180a290f8)

Extension version 43

System:
Fedora 38
GNOME 44.5

**Comment by pratap-panabaka** [comment]
Hi @luca-brambilla for hiding the user-switch, can you try running the below command

`gsettings set org.gnome.desktop.lockdown disable-user-switching true`

when you want to show it
`gsettings reset org.gnome.desktop.lockdown disable-user-switching`

Try this and get back to me is that Ok?
meanwhile let me fix the outer most button tooltip.

Thanks!

**Comment by pratap-panabaka** [comment]
Hi @luca-brambilla for text overlay issuse,
I am not able to update this extension for gnome-shell v44. I will fix that for gnome-shell v45.

as a quick fix,
can you adjust the value in `extension.js` file?

```
const LabelLauncher = new GObject.registerClass(
class LabelLauncher extends St.Widget {
_init() {
this.label = new St.Label({ style_class: 'dash-label' });
this.label.hide();
Main.layoutManager.addTopChrome(this.label);
}
 
showLabel(button) {
this.label.set_text(button.accessible_name);
this.label.opacity = 0;
this.label.show();
  
const center = button.get_transformed_position();
const x = center[0] - 20; // Line number 72
const y = 10;
```

change the value at line number 72 from 20 to 30 or 40 and see, like below
`const x = center[0] - 30`

**Comment by luca-brambilla** [comment]
Thank you very much! I was able to fix everything!

> change the value at line number 72 from 20 to 30 or 40 and see, like below `const x = center[0] - 30`

If I use a 2K display I had to push the value to 60, I noticed.

:)

**Comment by pratap-panabaka** [comment]
I will fix it in gnome 45.
Thanks for your response.
