### ISSUE TITLE
A gap between Settings and Lock buttons and incorrect shaping when disabling/enabling the extension.

### ISSUE THREAD

**Issue by kanannuruyevs** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#33]
Hi there. Great extension, but there appears to be a gap between these two buttons, not aligning each other very well:

![Screenshot from 2023-10-31 09-35-22](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/99095303/ac45704b-648a-4553-8b42-c0a73c6e8961)

Could it be due to Debian's original Systems Menu design? As default, it appears to be like this:

![Screenshot from 2023-10-31 09-39-09](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/99095303/0e0a2fcf-a785-42f6-b58b-fc1e94940a67)

I mean, if this is the case, then I am wondering if anything you should do about it.

Also, the other issue is this. When I disable/enable the extension, the buttons are incorrectly shaped, which only logging out and loggin in to the system helps:

![Screenshot from 2023-10-31 09-41-53](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/99095303/7c6dcee0-5059-4941-b4e3-892769d70e85)

I use Debian 12, GNOME 43.6.

Hopefully, you will be able to address the issue. Thanks.

**Comment by pratap-panabaka** [comment]
Hi @kanansnote , I will go through this one. Will get back to you soon. can you turnoff this extension and then provide me screenshot of the same.

Thanks

**Comment by pratap-panabaka** [comment]
Hi @kanansnote, I have edited my first comment, please review it. Right now I am on gnome-shell v45. I have to install fresh copy of Ubuntu which has 43 version. Can you provide the screenshot as per above comment please.

**Comment by kanannuruyevs** [comment]
OK, so the issue persists even I disable/enable the extension and only logging out/in helps. And by the way, I forgot to mention that this happens when I use removing/adding any buttons in the extension settings.

Wait, I disabled another extension that actually was related to Systems Menu Settings and tried to disable/enable options in yours, and then it's gone. The other extension was [User Avatar In Quick Settings](https://extensions.gnome.org/extension/5506/user-avatar-in-quick-settings/).

**Comment by pratap-panabaka** [comment]
Ok means when User Avatar Extension is enabled, then the issue of gap is there rite? other wise no?

**Comment by kanannuruyevs** [comment]
Not a gap, but incorrect shaping. The gap still exists.

**Comment by pratap-panabaka** [comment]
Ok if you disable this extension User Avatar, then `bringout` extension is working as expected?

**Comment by kanannuruyevs** [comment]
Do you mean shaping? Then, yes it is.

**Comment by pratap-panabaka** [comment]
Hey, I am not getting shaping and gap exactly.

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/2142fbf5-f5e6-453b-8a0a-cafd58a74b75)

This is in gnome-shell v45. I have added user avtar extension. Is there any thing you can explain from above image.

**Comment by pratap-panabaka** [comment]
Ok I understood after reading your first comments several times about `shaping`. This could be due to User Avtar Extension Settings, can you adjust the size from user-avtar settings, then we can notice the round shape to different shape. Lets confirm this and then look for refactoring the code.

**Comment by kanannuruyevs** [comment]
Ok, great. I am glad that we have a clear understanding of the shaping issue. When I adjust the user avatar size and then using your extension to turn on/off options:

Then, regarding the gap issue, let me again clarifying what I talk about. It seems that I am asking two issues at the same time, and maybe that's confusing a little bit.

So, when I say a gap, I mean the red lined area:

![Screenshot from 2023-10-31 09-35-22](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/99095303/8376ceb7-59b0-4e95-aec0-fde262d44de8)

Probably, I should say a space or something else. But English isn't my first language. So that's what I got.

And then in your screenshot, there is a single area that I showed within my screenshot. That's what I meant. In general, 

So, in my first comment, I was wondering if there is anything to do, as the gap between the buttons have in original Debian's menu design and by enabling your extension, the buttons are typically added between lock and close buttons that makes a gap shrinking a bit, standing between Settings and Lock Buttons.

**Comment by pratap-panabaka** [comment]
@kanansnote both the issues are very clear now. in fact space is given by default between them by gnome. I will try to refactor and provide you the code for that. Regarding the shaping, I am working on it. Will get back once I come to a solution.

Thanks!

**Comment by pratap-panabaka** [comment]
Hi @kanansnote. Can you open `extension.js` file and edit the content as per below?

func at line 233
```
_connectSettings() {

items.forEach((item, index) => {
let key = keys[index];
if (key)
item._buttonShowHide = this._settings.connect(`changed::${key}`, this._settingsChanged.bind(this, [item, key));
});
  
this._confirmId = this._settings.connect('changed::confirmation-dialog', this._confirmationDialogChanged.bind(this));
this._sMSId = this._sessionManagerSettings.connect('changed::logout-prompt', this._logoutPromptChanged.bind(this));
}
```
and func at line 244 with args
```
_settingsChanged(args) {
            const [button, key] = [...args]
            let isTrue = this._settings.get_boolean(key);
            if (isTrue) {
                button.hide();
            } else {
                button.show();
            }
        }
```

**Comment by kanannuruyevs** [comment]
That didn't work. After logging off/in, the extension broke and not functioning.

**Comment by pratap-panabaka** [comment]
Hi, Can you send me your `extension.js` file please

**Comment by kanannuruyevs** [comment]
https://dpaste.org/VW5Qw

**Comment by pratap-panabaka** [comment]
> https://dpaste.org/r7YQS

Hi, I am getting 404 snippet error

**Comment by kanannuruyevs** [comment]
Renewed. Please, take a look on edited comment.

**Comment by pratap-panabaka** [comment]
Hi, it is a one time snippet, once you open it, copy paste some where first and then replace your `extension.js` file with this contents.

https://dpaste.org/dyfp9

**Comment by pratap-panabaka** [comment]
> Renewed. Please, take a look on edited comment.

I found a typo in your code, args array was not closed. ex: `[item, key`

**Comment by kanannuruyevs** [comment]
Ok, well. That worked.

I guess it's time to close this issue. Thank you for the effort!

**Comment by pratap-panabaka** [comment]
Hi did you notice two more things along with that shape issue.
1. space between
2. on hover, tooltip.

I have changed those 2 things also in the given code. If you have any changes let me tell you.

Thanks

**Comment by kanannuruyevs** [comment]
Oh, wait. Yes, there is a change on that too.

**Comment by pratap-panabaka** [comment]
Line number 72 `extension.js` file. Adjust below value. Now its 40. Adjust to 60 or 80 something.

`const y = center[1] - 80`;

**Comment by pratap-panabaka** [comment]
Are you using laptop or desktop?
based on that,

line no 202 `extension.js` file. use this line
`
Main.panel.statusArea.quickSettings._system._systemItem._desktopSpacer.hide()
Main.panel.statusArea.quickSettings._system._systemItem._laptopSpacer.hide()`

and same in the `destroy` function like below. - line 288
`Main.panel.statusArea.quickSettings._system._systemItem._laptopSpacer.show();
`

Note: when you disable and enable the extension, the shape issue is still there.

**Comment by kanannuruyevs** [comment]
I'm using a laptop, so I added the given code lines to the JS file itself. For destroy function, I added `desktopSpacer` option, as there has `laptopSpacer` one already.

**Comment by pratap-panabaka** [comment]
You feel all ok? Do you need anything further?

**Comment by kanansnote** [comment]
Did you actually watch the entire video?

**Comment by pratap-panabaka** [comment]
Yes Kanansnote, 4 times watched. I asked because I might have missed something.

**Comment by kanannuruyevs** [comment]
Ok, let's end this conversation. I am done.
