### ISSUE TITLE
Missing Hibernate Button

### ISSUE THREAD

**Issue by 0Raik** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#34]
Hi, thanks for the great work made to improving Gnome with this extension. Previously (Gnome 44) we had the option to add the hibernate button, now with Gnome 45 the option is missing, and I miss it :(

Is it possible to add it back? or this is a new limitation with the changes Gnome made to the extensions?

Thank you for your time and have a good day.

**Comment by pratap-panabaka** [comment]
Hi @0Raik, I have not implemented it in GNOME 45. Is Hibernate working on your system? Do you have any command to test it? If you have the command, can you give me that. I will try to implement it.

Moreover there is a `Hibernate Status Button` with improved features, this extension is available from gnome-extensions. But these two extensions together can not work. I tried to tweak BringOut Extension to adapt thing from Hibernate Extension, but this extension has many new implementations that made me to dropout from that Idea.

Try Hibernate Extension, If you still need to keep BringOut Extension, Try to check for the command that makes your system hibernate or hibernate sleep and provide me those commands. I will try to implement it.

May I know your OS distribution name.

Thanks @0Raik

**Comment by pratap-panabaka** [comment]
Hi @0Raik I have tried to bring back that feature but hibernation completely depends on user system. My Arch Linux is not configured for hibernation or hybrid sleep. So I am not able to test. Download the below zip file.

[bosm_hibernation.zip](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/files/13325987/bosm_hibernation.zip)

change directory to downloaded zip file. and then run below command.

`gnome-extensions install -f bosm_hibernation.zip`

Alt+f2 r Enter if you are on Xorg, if you are on Wayland, then logout and login.
Enable the extension and see.

Thanks

**Comment by 0Raik** [comment]
Thanks for the quick response!
Yes. The command I can use to hibernate

`systemctl hibernate`

Using Manjaro latest stable.

Will try the new extension as see how it goes.

Update: Thanks a lot! It worked as it did back with Gnome 44. Hibernates and wakes ups as normal, thanks and have an excellent day!

**Comment by pratap-panabaka** [comment]
Hi @0Raik,
I have implemented confirmation for **HybridSleep** and **Hibernation** Buttons. Would you like to try it?

**Comment by mokilcde** [comment]
I will try it also!

**Comment by pratap-panabaka** [comment]
@mokilcde Here it is. [bosmExtension.zip](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/files/13335559/bosmExtension.zip)

Once you downloaded the file,

`gnome-extensions install -f  bosm_v49.zip`.

Refresh the shell with Alt+f2 r Enter or logout and login.

Then enable the extension. Go to extension settings and turn on the two buttons.

Thanks

**Comment by mokilcde** [comment]
The version in the download is 46 and do not have the hibernate button included

**Comment by pratap-panabaka** [comment]
> @mokilcde Here it is. [bosmExtension.zip](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/files/13335559/bosmExtension.zip)
> 
> Once you downloaded the file,
> 
> `gnome-extensions install -f bosmExtension.zip`.
> 
> Refresh the shell with Alt+f2 r Enter or logout and login.
> 
> Then enable the extension. Go to extension settings and turn on the two buttons.
> 
> Thanks

Hi v49 is not yet uploaded to extensions for review. Please use this zip file. bosmExtension.zip

**Comment by pratap-panabaka** [comment]
![bosm_v49](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/b47a4749-1ec4-4461-823a-6c18a223c33d)

**Comment by mokilcde** [comment]
No settings:

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/43954271/2aca3166-1c08-4633-bbda-0bc6b4afb8d4)

No hibernate

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/43954271/8b3b2416-263e-4532-a61a-8caca349c39b)

```
cd .local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton\@pratap.fastmail.fm/
michael@k-c13:BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm$ ls -lt
total 52
drwxr-xr-x 2 michael k-c13 4096 Nov 13 14:13 schemas
-rw-r--r-- 1 michael k-c13 4540 Nov 13 11:16 CreateActionItem.js
drwxr-xr-x 2 michael k-c13 4096 Nov 13 11:09 Hibernation
-rw------- 1 michael k-c13  535 Nov 12 09:27 metadata.json
-rw-r--r-- 1 michael k-c13 7984 Nov 12 04:27 BringoutMenu.js
-rw-rw-r-- 1 michael k-c13 1300 Nov 12 04:18 extension.js
-rw-r--r-- 1 michael k-c13 2898 Nov 12 04:00 SyncLabel.js
drwxr-xr-x 2 michael k-c13 4096 Nov 11 14:46 icons
drwxr-xr-x 2 michael k-c13 4096 Nov 11 11:10 prefs
-rw-r--r-- 1 michael k-c13   49 Nov  6 07:03 stylesheet.css
-rw-r--r-- 1 michael k-c13 1602 Nov  6 06:41 LabelLauncher.js
```

I saw the dialogs in `CreateActionItem.js`

**Comment by pratap-panabaka** [comment]
Hi can you share me extensions settings page like this?

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/5b094b0b-0321-4876-8b31-38ed7f9a43fe)

**Comment by pratap-panabaka** [comment]
> No settings:
> 
> ![image](https://user-images.githubusercontent.com/43954271/282477518-2aca3166-1c08-4633-bbda-0bc6b4afb8d4.png)
> 
> No hibernate
> 
> ![image](https://user-images.githubusercontent.com/43954271/282477661-8b3b2416-263e-4532-a61a-8caca349c39b.png)
> 
> ```
> cd .local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton\@pratap.fastmail.fm/
> michael@k-c13:BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm$ ls -lt
> total 52
> drwxr-xr-x 2 michael k-c13 4096 Nov 13 14:13 schemas
> -rw-r--r-- 1 michael k-c13 4540 Nov 13 11:16 CreateActionItem.js
> drwxr-xr-x 2 michael k-c13 4096 Nov 13 11:09 Hibernation
> -rw------- 1 michael k-c13  535 Nov 12 09:27 metadata.json
> -rw-r--r-- 1 michael k-c13 7984 Nov 12 04:27 BringoutMenu.js
> -rw-rw-r-- 1 michael k-c13 1300 Nov 12 04:18 extension.js
> -rw-r--r-- 1 michael k-c13 2898 Nov 12 04:00 SyncLabel.js
> drwxr-xr-x 2 michael k-c13 4096 Nov 11 14:46 icons
> drwxr-xr-x 2 michael k-c13 4096 Nov 11 11:10 prefs
> -rw-r--r-- 1 michael k-c13   49 Nov  6 07:03 stylesheet.css
> -rw-r--r-- 1 michael k-c13 1602 Nov  6 06:41 LabelLauncher.js
> ```
> 
> I saw the dialogs in `CreateActionItem.js`

Oh sorry, you mentioned that 'No Settings'. Is your OS Ubuntu 23.10?

**Comment by mokilcde** [comment]
Debian SID/Experimental

**Comment by pratap-panabaka** [comment]
Hi @mokilcde Sorry. I just shifted to Ubuntu 23.10 OS from Arch to test why the prefs are missing. Somehow the file is missed in zip file I shared.

Please use this file, I have tested this zip file.

[bosmExtension.zip](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/files/13335559/bosmExtension.zip)

Thanks

**Comment by mokilcde** [comment]
Great! Back again. But why they are white
![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/43954271/eb560b73-4d29-44ed-9591-1e258e617bc0)

**Comment by pratap-panabaka** [comment]
Hi, there are no system-icons(from GNOME) for those, so I have downloaded and put them in the extensions icon folder. you can change them with any icon you prefer. Or open those files with text editor and change the `fill` color to your wish.

**Comment by pratap-panabaka** [comment]
Hi @mokilcde I did a workaround for it. To inherit the theme colors for these two buttons dynamically. Please download this zip file and install the extension as usual. Then copy the two icons from extensions `icons` folder and paste in `.icons` folder of users home directory.

[bosmExtensionIconColor.zip](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/files/13335816/bosmExtensionIconColor.zip)

This way, it uses the shell theme color.

Thanks

**Comment by pratap-panabaka** [comment]
Arch Linux - Automatic White

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/ce483ffe-bb9a-491b-82f1-c01b99537631)

**Comment by pratap-panabaka** [comment]
Ubuntu 23.10 - Black

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/9e9672ac-3d71-473c-8c3f-b7a9443fcc6d)

**Comment by mokilcde** [comment]
Great! I often use this extension so I am happy that it works again.

I hope that you release it and with the next version it is already included

**Comment by pratap-panabaka** [comment]
Hi, Yes I will final test it and submit for review. These days gnome-extensions review is taking so long I observed.

Thanks for your testing on this extension. Have you copied the icons from extensions `icons` folder to `.icons` of home directory?

**Comment by mokilcde** [comment]
Great! I often use this extension so I am happy that it works again.

I hope that you release it and with the next version it is already included

**Comment by mokilcde** [comment]
I did not copy anything. I only installed your extension.

**Comment by pratap-panabaka** [comment]
> Hi @mokilcde I did a workaround for it. To inherit the theme colors for these two buttons dynamically. Please download this zip file and install the extension as usual. Then copy the two icons from extensions `icons` folder and paste in `.icons` folder of users home directory.
> 
> [bosmExtensionIconColor.zip](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/files/13335816/bosmExtensionIconColor.zip)
> 
> This way, it uses the shell theme color.
> 
> Thanks

This is going to be the one that will be uploaded to gnome-extensions. So please install the extension from this zip file and then copy those icons to your `.icons` folder of home directory. other wise you wont see icons for those buttons.
