### ISSUE TITLE
Extension startup failed with 22.04.1-Ubuntu

### ISSUE THREAD

**Issue by TeeHip** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#35]
Error print: import declarations may only appear at top level of a module

**Comment by pratap-panabaka** [comment]
Hi @TeeHip can you provide the contents of your extensions `metadata.json` file please.

Thanks

**Comment by TeeHip** [comment]
Hi. 

It's here:

cat ~/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/metadata.json
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Bring Out Submenu Of Power Off/Logout Button and Rearrange the Order of System Menu.",
  "name": "Bring Out Submenu Of Power Off/Logout Button",
  "settings-schema": "org.gnome.shell.extensions.brngout",
  "shell-version": [
    "45"
  ],
  "url": "https://github.com/PRATAP-KUMAR/Bring-Out-Submenu-of-Power-Off-Logout",
  "uuid": "BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm",
  "version": 46
}

**Comment by pratap-panabaka** [comment]
Hi @TeeHip thanks for the output.
You mentioned 22.04 Ubuntu. You should download shell-version 44. You are using the extension that is made for v45/23.10

**Comment by TeeHip** [comment]
Hi.

Thanks for support but now am having the error:
**Main.panel.statusArea.quickSettings is undefined**

_cat ~/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/metadata.json 
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Bring Out Submenu Of Power Off/Logout Button and Rearrange the Order of System Menu.",
  "name": "Bring Out Submenu Of Power Off/Logout Button",
  "settings-schema": "org.gnome.shell.extensions.brngout",
  "shell-version": [
    "44"
  ],
  "url": "https://github.com/PRATAP-KUMAR/Bring-Out-Submenu-of-Power-Off-Logout",
  "uuid": "BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm",
  "version": 43_

**Comment by PRATAP-KUMAR** [comment]
Hi @TeeHip can we have a zoom or google meet?

**Comment by pratap-panabaka** [comment]
Hi @TeeHip oh I am sorry. Ubuntu 22.04 shell version is not 44. I am very sorry for my mistake, instead of 22.04 I told you 23.04 version.

Can you provide the output of 

`gnome-shell --version`

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/e5e013b3-5d4c-49af-b5e8-d2ef621bb69b)

Based on the output download the extension and install it.

**Comment by TeeHip** [comment]
Hi.

No problem and thansk for help. I checked it quickly =>

__:~$ gnome-shell --version
GNOME Shell 42.9

__:~$ uname -a
Linux srpropro-ThinkPad-T495 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by TeeHip** [comment]
I installed 29 version and now everything is working fine :) Big thanks for support.
