### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by foXaCe** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#37]
Hello

very good job

how to add french translation please ?

**Comment by PRATAP-KUMAR** [comment]
Hi @foXaCe, I have never done translations to any of my extensions because I dont know. But if you would like to add your self, you can go through this wonderful guide https://gjs.guide/extensions/development/translations.html#preparing-an-extension

I will help you if you start working on it or if you want me to do it then I will take your help.

Thanks

**Comment by foXaCe** [comment]
@PRATAP-KUMAR  thank for your answer but that very hard for me

**Comment by PRATAP-KUMAR** [comment]
Ok I will try to understand how to proceed with translations, as far as I know, I think I have to take your help on french wording..
lets see, when I come across this translation of words, I will ping you.

Thanks

**Comment by PRATAP-KUMAR** [comment]
@foXaCe translation for extension settings or for tool tip are you looking for? or for both?

**Comment by foXaCe** [comment]
very good thanks you for all

**Comment by foXaCe** [comment]
for both

**Comment by PRATAP-KUMAR** [comment]
Ok I will get back to you in a day or two.

**Comment by foXaCe** [comment]
merci

**Comment by PRATAP-KUMAR** [comment]
Hi @foXaCe 

What is your locale out of these
```
#fr_BE.UTF-8 UTF-8
#fr_BE ISO-8859-1
#fr_BE@euro ISO-8859-15
#fr_CA.UTF-8 UTF-8
#fr_CA ISO-8859-1
#fr_CH.UTF-8 UTF-8
#fr_CH ISO-8859-1
#fr_FR.UTF-8 UTF-8
#fr_FR ISO-8859-1
#fr_FR@euro ISO-8859-15
#fr_LU.UTF-8 UTF-8
#fr_LU ISO-8859-1
#fr_LU@euro ISO-8859-15
```

**Comment by foXaCe** [comment]
#fr_FR.UTF-8 UTF-8
#fr_FR ISO-8859-1
#fr_FR@euro ISO-8859-15

**Comment by PRATAP-KUMAR** [comment]
Ok thank you @foXaCe,

I will give you one `pot` file in a day or two. can you translate the text with the tool https://flathub.org/apps/details/org.gnome.Gtranslator or with this https://flathub.org/apps/details/net.poedit.Poedit or you can even write the translation your own on the `pot` file which I am going to generate and give you.

**Comment by foXaCe** [comment]
ok no problem

**Comment by pratap-panabaka** [comment]
Hi @foXaCe Can you check these translations, I just google translate them one by one

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/592f9d62-5e60-4f5e-9de5-84d383ff82b5)

**Comment by foXaCe** [comment]
typo  "Masquer le bouton de déconnections"
hide restart button = Masquer le bouton de redémarrage

and everything else is good, well done and thank you very much

**Comment by foXaCe** [comment]
may be an encoding problem with special characters like   "é"

**Comment by PRATAP-KUMAR** [comment]
Ok I guess there are hardly less than 25 translations so I give you the file and you fill those translations. Tomorrow we shall finalize this. Its 10pm for me now.

**Comment by foXaCe** [comment]
ok no problem 

merci beaucoup

**Comment by pratap-panabaka** [comment]
Hi @foXaCe 
Good day

Can you download the repo n use "**fr-translation**" branch.
Install the extension with **Makefile**
```
make
make install
```
Once the extension works normally with English, then copy the `locale` directory from downloaded repo to extensions root

Refresh the shell or logout and login to see the change.

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/b2ee7871-5304-4521-a359-74f2a3dfca5c)

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/f2b2b372-7f4a-43ae-8a50-468cf758b3b2)

Thanks

**Comment by foXaCe** [comment]
hello

where is " to extensions root" ?

**Comment by PRATAP-KUMAR** [comment]
‘’’
.local/share/gnome-shell/extensions/bring-out-submenu-of-power-off-logout@pratap.fastmail.fm
‘’’
typing from mobile. Check for typos

**Comment by foXaCe** [comment]
![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/290678/0ad195ad-f35d-4761-9998-52b93f7cc853)


sorry i have a noob on linux

**Comment by foXaCe** [comment]
I can't find your extension

**Comment by PRATAP-KUMAR** [comment]
Zoom or Google meet??

**Comment by foXaCe** [comment]
This is my workstation
not from my house
I don't have access to zoom or meet

**Comment by foXaCe** [comment]
maybe a cmd line to copy paste

**Comment by PRATAP-KUMAR** [comment]
Oh thats Ok.
Have you used this extension before??

**Comment by PRATAP-KUMAR** [comment]
Ok I will give you commands

**Comment by foXaCe** [comment]
yes

**Comment by foXaCe** [comment]
![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/290678/9ac9832e-d867-433a-b1f5-197d68e61efe)

**Comment by PRATAP-KUMAR** [comment]
Can you share screenshot of top right menu

**Comment by PRATAP-KUMAR** [comment]
gnome-extensions list

run this command n share output

**Comment by foXaCe** [comment]
![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/290678/7fb14234-1c35-44af-94d4-a029221e368e)

**Comment by pratap-panabaka** [comment]
Hi @foXaCe can you run this command
```
gnome-extensions list
```
![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/84c84931-8ada-4aa8-97cd-2232c079d8aa)

**Comment by foXaCe** [comment]
![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/290678/9fb58c18-9d0b-4f32-bc4f-a7cade4a981d)

**Comment by PRATAP-KUMAR** [comment]
Ok, in order to start from scratch, you need to remove two extensions with below commands

gnome-extensions uninstall BringOut........................fastmail.fm
gnome-extensions uninstall bring-out.......................fastmail.fm

are you willing to do?

**Comment by foXaCe** [comment]
yes

**Comment by PRATAP-KUMAR** [comment]
If your system is admined by someone else, then probably bringout extension is installed system wide. but try to remove with above two commands

**Comment by foXaCe** [comment]
good now ?

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/290678/58c4acc5-e329-408f-a8f1-f551853c7ef2)

**Comment by pratap-panabaka** [comment]
great.. download this zip file and **dont unzip it**. once you downloaded, run the below command and share the output
```
ls | grep brngout_ext_fr.zip
```
[brngout_ext_fr.zip](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/files/13390283/brngout_ext_fr.zip)

**Comment by foXaCe** [comment]
![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/290678/cd7925ef-7894-42f4-abd5-8701673547b6)

**Comment by foXaCe** [comment]
done

**Comment by foXaCe** [comment]
![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/290678/624bd419-efc1-4cea-91f5-4ccb569970ee)

**Comment by PRATAP-KUMAR** [comment]
Nice, refresh the gnome-shell with Alt+F2 r enter method. or if you are on wayland then logout and login.
Once above is done then again check for output of below command

```
gnome-extensions list | grep bring-out
```

**Comment by foXaCe** [comment]
Yes it works
well done and thank you for your help
you are a very wonderful person

**Comment by foXaCe** [comment]
Good day to you
