### ISSUE TITLE
Getting Bring Out Submenu Of Power Off Button latest version

### ISSUE THREAD

**Issue by Jai-GAY** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#39]
I installed it through sudo apt-get install [gnome-shell-extension-manager](https://github.com/mjakeman/extension-manager).

But it seems like I am [having version 29 and not 45, the latest](https://extensions.gnome.org/extension/2917/bring-out-submenu-of-power-offlogout-button/)

Would you happen to know why?

![22 04 3 64-bit_poweroff_issue2](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/12781023/b5fbf13f-3ce1-4951-8c5f-d21b23958741)

**Comment by pratap-panabaka** [comment]
Hi how did you install the extension? any commands or GUI way. Please let me know them.
Also please provide the output of below command from terminal

`gnome-shell --version`

**Comment by Jai-GAY** [comment]
> how did you install the extension?

GUI, via browse and search in the next tab.

okay, I think I am in[ Gnome version 42 which is under Ubuntu 22.04 LTS](https://www.omgubuntu.co.uk/2022/10/how-to-upgrade-to-ubuntu-22-10-from-22-04), therefore only version 29. Is there a way to have the latest for Gnome version 42?

Appreciate the quick response and wish you a good successful year ahead.

<img width="472" alt="image" src="https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/12781023/059f896a-4541-40da-9ef2-082994140db6">

**Comment by pratap-panabaka** [comment]
Hi @Jai-GAY thanks for your response on my queries.
Oh sorry, I dont have plans to update this extension for gnome-shell version 42.
There is a much transformation from gnome-shell v <= 44 and latest v = 45.

Sorry again.
