### ISSUE TITLE
Menu order

### ISSUE THREAD

**Issue by galen1423** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#4]
Hi,

Can you consider in a next time, to be able to change elements order in the menu? Personally, I wish I could see mine in this order : 
- ....
- ....
- Settings
- Logout
- Lock
- Power

Thanks for your code. :)

**Comment by PRATAP-KUMAR** [comment]
ya thats possible you dont need suspend?

**Comment by pratap-panabaka** [comment]
yes.. sure.. its a nice idea.. I will try an update..
