### ISSUE TITLE
Version 29 on Gnome 42, Ubuntu 22.04

### ISSUE THREAD

**Issue by Jai-GAY** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#40]
How come I do not see [those buttons mentioned on the readme page](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout?tab=readme-ov-file#action-buttons)?

![22 04 3 64-bit_poweroff_issue4](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/12781023/efc59a28-3a07-4e2f-b77f-17cc70b77190)

**Comment by pratap-panabaka** [comment]
Hi @Jai-GAY 

Sorry for that. The Readme is for V45 which is the latest version of GNOME.
