### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kwyxz** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#41]
Hello! Love this extension and it fits my needs perfectly but I was wondering what kind of License it is using? I could not find any mention of it. Thank you!

**Comment by pratap-panabaka** [comment]
Hi @kwyxz 
It is GPL 3.0, I have added the license.

Thanks for raising this issue.

**Comment by kwyxz** [comment]
Thank you! Much appreciated
