### ISSUE TITLE
Logout icon reappears on reboot, Ubuntu 24.04

### ISSUE THREAD

**Issue by ninodeuruguay** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#42]
Ubuntu 24.04 with gnome 46, Bring Out Submenu Of Power Off Button v54.

It is set so that the logout icon does not appear, but when rebooting, it reappears.

Greetings.

**Comment by pratap-panabaka** [comment]
Hi
I didn't understand.
Can you explain it please.

Thanks.

**Comment by ninodeuruguay** [comment]
You set the configuration in the extension to hide the logout icon and it does.

When you restart the operating system, the logout icon reappears.

**Comment by pratap-panabaka** [comment]
Oh ok,
I will look into it in a week

Thanks

**Comment by pratap-panabaka** [comment]
@ninodeuruguay Hi,

I have gone through the latest release gnome-shell v46.2 and found that slight changes in the source code are making the logout button appear even though extension settings are set to hide this button.

I removed the system bindings so the extension buttons stick to the settings.

I have uploaded the extension v55 for review from gnome-extensions.
If you wish to test it now, you can download the zip file from here https://extensions.gnome.org/review/download/55806.shell-extension.zip

![image](https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/assets/40719899/ac24c023-9c46-46da-aab8-ce35d42e5703)

```
gnome-extensions install -f BringOutSubmenuOfPowerOffLogoutButtonpratap.fastmail.fm.v55.shell-extension.zip
```

Logout and login.

Thanks

**Comment by ninodeuruguay** [comment]
Thank you very much, it automatically updated to version 56 of the extension and now works perfectly with Ubuntu 24.04.
