### ISSUE TITLE
no "logout" icon

### ISSUE THREAD

**Issue by frosth555** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#5]
Hi, The "Logout" icon is missing from menu, and there is no system-logout-symbolic in my system
I found system-log-out-symbolic instead. 

Archlinux, Gnome-3.36.2, Icons Theme - Adwaita

**Comment by pratap-panabaka** [comment]
Hi frosth555 Can you install the v7 of the extension and open the `extension.js` file and edit the content like below..
```
//
_createMenu: function() {
logout = new PopupMenu.PopupImageMenuItem(_('Logout'), 'system-log-out-symbolic');
logout.connect('activate', () => { this._systemActions.activateLogout(); });
```

**Comment by frosth555** [comment]
oh, sorry 
I should write I change this line in extension.js and it works.

**Comment by pratap-panabaka** [comment]
Can I close the issue?

**Comment by frosth555** [comment]
In original extension.js is "system-logout-symbolic" still, so it's confusing me a little bit. But I have my icon in place :) So yes we can close it. 

BTW thanks for great extension.

**Comment by pratap-panabaka** [comment]
@frosth555 its my mistake, I have corrected it and uploaded to https://extensions.gnome.org/ It will be available soon with the correction.. Thanks for your reporting.
