### ISSUE TITLE
Missing features with latest extensions.gnome.org version

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#6]
Hi @PRATAP-KUMAR !

With the latest extensions.gnome.org update _(what I got yesterday)_ I missed the some weeks ago restructured menu order, while not got dconf settings what you mentioned in the new screencast at extensions.gnome.org.

<p align="center"><img src="https://user-images.githubusercontent.com/25765137/81787861-efdd8700-9501-11ea-8bc3-74f257a3ef4d.png" width="200" /></p>

I tried to uninstall and reinstall the extension but nothing changed.

Have you any opinion about it?

**Comment by pratap-panabaka** [comment]
Hi, Thanks for pointing out..

and sorry for the re-order of the menu items in latest version, I don't know about  "extensions.gnome.org" or "GNOME" have the capability to update the extension to latest version it self without user interaction.

v5 which is old one is still available at extensions website. If you don't prefer this v7 (yesterdays update).. please use v5 until next update comes which is targeted to control the Menu Order based on User Choice..

v7 is prepared based on 2 user reviews, clearly mentioned in `readme` file.

There are 3 Options for v7 extension you can use via `dconf editor` or command line `gsettings`. you need to compile the schemas first.

go the the extensions folder `$HOME/.local/share/gnome-shell/extensions/BringOut..../schemas/`

1. copy the file `org.gnome.shell.extensions.brngout.gschema.xml` which is inside schemas directory to `$HOME/.local/share/glib-2.0/schemas/` Create the Directory's as Necessary.

2. and run the command `glib-compile-schemas .`  from the directory `$HOME/.local/share/glib-2.0/schemas/`

![copy this](https://user-images.githubusercontent.com/40719899/81795920-59718b80-952a-11ea-8b2f-c9bfd1af4c77.png)

![paste here](https://user-images.githubusercontent.com/40719899/81795935-5f676c80-952a-11ea-9547-6c1c4178aaf3.png)

Once you compiled schemas.. you can use `dconf-editor` or command line `gsettings`

Thank you..

**Comment by pratap-panabaka** [comment]
Hi, I have created a new `extension.js` file. Replace the `extension.js` file which is in v7 with this file to have the same menu order along with capability to remove suspend and power buttons..

https://github.com/PRATAP-KUMAR/Re_Arrange_System_Menu_Items/blob/test/extension.js

![menu Order same as in v5](https://user-images.githubusercontent.com/40719899/81805605-d0158580-9538-11ea-957e-9bbca04e537e.png)

![5](https://user-images.githubusercontent.com/40719899/81805846-36020d00-9539-11ea-9e43-7c4b3349a5ab.gif)

**Comment by Tamas-Toth-ebola** [comment]
Hi again!

Thanks the very detailed informations and your time for it. Luckily I'm relatively familiar with Gnome Shell extensions as I made some experiences for myself just as hobby and correct some others with bugfixes and functions expansions. So really do not take so much time for my messages as I will patiently wait if there is any bug, and if not just I need to do some manual extra steps, I could, and I will.

A Gnome Shell extensions store their configuration data in dconf backend your mentioned steps are totally understandable just I simply did not checked that the extension itself does not have it/or make it yet.

In the future it would be nice if through extensions.gnome.org this could be automatically available, and if the extension would have it's own config panel instead of manual dconf editing but of course these things are just the final polishings of the extension itself and they are very far from the basic 'mandatory' features.

Very lot of thanks again for your answer and also for your efforts on the extension.

**Comment by pratap-panabaka** [comment]
Thanks for your response.. Yes I agree with your point on "own config panel instead of manual dconf editing" I hope will achieve that in upcoming days along with the capability to change the Menu order as per user wish..

**Comment by drzraf** [comment]
![Screenshot from 2020-05-17 19-03-48](https://user-images.githubusercontent.com/1169926/82161230-60253900-9871-11ea-953d-8ebe60437c1a.png)

Is it possible to remove lock & logout using this extension?

**Comment by pratap-panabaka** [comment]
Hi, Lock can be removed out of the box option.
Same to Logout also but It will hide Power Off button too..

```
gsettings set org.gnome.desktop.lockdown disable-log-out true
gsettings set org.gnome.desktop.lockdown disable-lock-screen true

```

![Image](https://user-images.githubusercontent.com/40719899/82161677-57a62000-98bc-11ea-99ff-e834ac762530.png)

**Comment by drzraf** [comment]
But `disable-lock-screen` not only remove the button, but the feature. My keybinding for lock-screen would stop working too.

**Comment by pratap-panabaka** [comment]
thats rite.. disable means it will disable.. you cant lock in any manner. or you want to lock with keyboard shortcut and don't want to see it in system menu?
