### ISSUE TITLE
Menu Item Labels break Localization

### ISSUE THREAD

**Issue by stemabu** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#8]
Hi,
the extension works fine, but except "Suspend" it does not use the "original" labels of the menu items. Therefore, the translation of the menu items does not work in non-English versions of Ubuntu, and they appear in English. The differences between the "original" labels and the one in the extension are quite small (but effective...). I tried a little bit back and forth, and the following changes of the labels in the code of your extension.js let the localization work again for me:
...
`logout = new PopupMenu.PopupImageMenuItem(_('Log Out'), 'system-log-out-symbolic');`
...
`switchUser = new PopupMenu.PopupImageMenuItem(_('Switch User…'), 'system-switch-user-symbolic.svg');`
...
`power = new PopupMenu.PopupImageMenuItem(_('Power Off…'), 'system-shutdown-symbolic');`
...
(Please note that for Swich User and Power Off it's the 3-dot-Char you can reach via Alt-. and not three single dots, which does not work)
Regards,
Martin

**Comment by pratap-panabaka** [comment]
Thank you, I understand ur point. I will try to update..

**Comment by brunob** [comment]
Hi and thx for this addon, i see that #11 was merged so this issue may be closed, but version 9 on ubuntu 20.04 still shows unlocalised items. Could you report #11 for gnome shell 3.36, i can provide a pr for that but i don't know which branch of the project is for 3.36.

I've backported the changes from #11 in `/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm/extension.js` and it fix the bug.

**Comment by pratap-panabaka** [comment]
Hi, Sorry for late reply.. for 3.36 v9 is the branch.. please proceed with the pr

**Comment by brunob** [comment]
> Hi, Sorry for late reply.. for 3.36 v9 is the branch.. please proceed with the pr

Done :)

**Comment by brunob** [comment]
This issue could be closed ;)
