### ISSUE TITLE
Introduce a proper master branch

### ISSUE THREAD

**Issue by owzim** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#9]
Hi, love this extension. Thanks a lot for that. Should be default behavior. The new gnome workflow is tedious at best.

Could you please have a proper `master` branch and not change the branch name all the time? If you introduce features or progress on development, do it in a separate branch and merge it into master if it is stable.

Otherwise this makes it hard to use the repo in packages or install scripts.

Cheers!

**Comment by pratap-panabaka** [comment]
Hi.. Sorry for that.. Actually today when I was creating a new branch leaving the master branch alone.. by mistake I deleted the files from master branch..

Can you help me to rename 'v8' as 'master'

I agree with you.. I will not change `master` branch in any case..

**Comment by owzim** [comment]
When you're in your `v8` branch `git branch master && git checkout master` then your master will be the same as `v8`. Then you can push.

**Comment by pratap-panabaka** [comment]
@owzim Thanks for your support.. I am very new to git.. I will study your above commands and try to achieve.. mean while go through this bounty https://stackoverflow.com/questions/62442139/how-to-make-a-uploaded-file-in-github-chmod-x-and-then-download-the-file-with to understand that I am very new to git..

**Comment by pratap-panabaka** [comment]
Hi I tried your git commands.. struggled a  bit to understand the concept.. at git push command it gave me some suggestion and I copy pasted that suggested command.. seems master branch is created.. small change is that instead of v8 I made v9 as master.. Can you check master branch is working or not? Thanks for your suggestion and support..
